### ISSUE TITLE
layout的内边距没有严丝合缝?

### ISSUE THREAD

**Issue by jhgf007225** [lirongtong/miitvip-vue-admin-manager#10]
mi-layout-content的padding-top为啥不是10.5rem  我这咋多出来一块边距呢

另外个人感觉面包屑单独占一行感觉好占地方

**Comment by lirongtong** [comment]
1. header 为 4rem，面包屑 + 历史路由 = 6.5rem，而我设定的是 11.5rem，多出的 1.5 算是 content 的 padding-top .
2. 面包屑后续考虑放在收缩菜单的按钮旁，这样就可以不独占一行了（ 最近实在因项目忙，有一段时间没有更新这个开源项目了  ）.
