### ISSUE TITLE
滑动验证码 vue2 的项目引入怎么报错  vue2 不兼容vue3吗

### ISSUE THREAD

**Issue by xuezhihuixzh** [lirongtong/miitvip-vue-admin-manager#11]
vue2 的项目引入怎么报错  vue2 不兼容vue3吗

![image](https://user-images.githubusercontent.com/46469901/132934182-2b52fc3b-187f-4b07-a05e-5655ea85c643.png)
![image](https://user-images.githubusercontent.com/46469901/132934203-c128d014-e537-4b2d-85c0-5b1daf6cc836.png)
![image](https://user-images.githubusercontent.com/46469901/132934205-fab621b7-e161-4780-b3ed-30cd5cf2b2df.png)
![image](https://user-images.githubusercontent.com/46469901/132934206-d42b762a-eec7-4d33-86fe-5ee1291fdf79.png)

**Comment by lirongtong** [comment]
vue 2 / 3 不兼容
