### ISSUE TITLE
captcha后台参数校验验证码，数据丢失问题

### ISSUE THREAD

**Issue by usmallorange** [lirongtong/miitvip-vue-admin-manager#15]
数据赋值代码截图
![image](https://github.com/lirongtong/miitvip-vue-admin-manager/assets/106041100/824a83a1-b893-4a66-b7db-a6bb5aad5e84)
数据绑定
![image](https://github.com/lirongtong/miitvip-vue-admin-manager/assets/106041100/32df4fcb-610d-4478-8b0b-42854f73aca1)
拿初始化数据
![image](https://github.com/lirongtong/miitvip-vue-admin-manager/assets/106041100/525a2c3c-1636-4aaa-9363-57e43e6db6f2)
后台校验没有携带参数
![image](https://github.com/lirongtong/miitvip-vue-admin-manager/assets/106041100/fc8db540-05e9-4f5f-a9a9-64e3ac2871bf)

**Comment by shyXcc** [comment]
添加初始化数据
![image](https://github.com/lirongtong/miitvip-vue-admin-manager/assets/106041100/bd7a1e83-6d20-432f-8da1-a9da4d352279)
后台校验就携带有参数了
![image](https://github.com/lirongtong/miitvip-vue-admin-manager/assets/106041100/e34a01d4-f123-47ae-b577-d0420e8a2758)

**Comment by lirongtong** [comment]
已修正
