### ISSUE TITLE
captcha发送验证数据，只能带到初始时候的数据

### ISSUE THREAD

**Issue by shyXcc** [lirongtong/miitvip-vue-admin-manager#16]
https://user-images.githubusercontent.com/106041100/274464287-824a83a1-b893-4a66-b7db-a6bb5aad5e84.png
https://user-images.githubusercontent.com/106041100/274464110-32df4fcb-610d-4478-8b0b-42854f73aca1.png
https://user-images.githubusercontent.com/106041100/274464475-fc8db540-05e9-4f5f-a9a9-64e3ac2871bf.png

**Comment by lirongtong** [comment]
新版的已经更新啦：npm i @miitvip/admin-pro
