### ISSUE TITLE
makeit-captcha2.0.7版本不更新了吗，请问2.0.7版本的滑块验证有多语言国际化吗

### ISSUE THREAD

**Issue by zym163** [lirongtong/miitvip-vue-admin-manager#17]

**Comment by lirongtong** [comment]
最近暂时没有更新的打算，不好意思，也不打算抽离成独立的组件了，需要的话，可以安装 @miitvip/admin-pro 单独引入 captcha 组件来使用 https://admin.makeit.vip/component/captcha
