### ISSUE TITLE
我在使用ElementPlus的ElMessageBox组件时，发现遮罩层无法遮盖菜单处，我该怎么修改？

### ISSUE THREAD

**Issue by zhoulongyaun** [lirongtong/miitvip-vue-admin-manager#19]
如下图：
![image](https://github.com/user-attachments/assets/ac8ef679-a6d7-4ab0-8002-4f26e1617062)
我在此处，使用ElementPlus的组件【ElMessageBox】弹框，进行一个简单的提示。但是发现菜单处却无法遮盖。
我查看后发现，是本系统设置的z-index（默认：20240110）远大于 ElementPlus的z-index（默认：2000）。
系统的z-index截图：
![image](https://github.com/user-attachments/assets/ded64907-9a74-4aba-b89b-5fc656f4d677)

**我该怎么修改本系统的z-index？**

**Comment by lirongtong** [comment]
layout 暂时不支持定制 z-index，回头我考虑加个配置；
现阶段你可以考虑用 ElMessageBox 的配置参数 customClass 或 customStyle 先设定 z-index
