### ISSUE TITLE
忘记密码页面无法调用正确

### ISSUE THREAD

**Issue by hufaei** [lirongtong/miitvip-vue-admin-manager#20]
忘记密码发送验证码之后的更新密码操作点击提交操作，报错：当前操作不被允许，我认为是我代码的问题实际上我直接使用官网的代码也会如此

**Comment by lirongtong** [comment]
过几天我重新发个版本，后面我有重新调整测试过，主要前段时间整理语言管理组件，想等这个页面组件做好之后一起发个版本的 ～
