### ISSUE TITLE
直接引入使用默认的就会报错 是我哪里没写对吗？

### ISSUE THREAD

**Issue by kshq1996** [lirongtong/miitvip-vue-admin-manager#4]
直接引入使用默认的就会报错 是我哪里没写对吗？
环境：vue3 + vite + macOS

index.js:16 Uncaught ReferenceError: process is not defined
    at makeit-captcha.js:1094

![image](https://user-images.githubusercontent.com/25955989/115832096-0ba51900-a445-11eb-8923-11b3eba5c3cd.png)

**Comment by kshq1996** [comment]
解决了 
在 vite.config.js  中
```
import {defineConfig, loadEnv} from 'vite';

export default ({mode}) => {
    process.env = {...process.env, ...loadEnv(mode, process.cwd())};
    // import.meta.env.VITE_NAME available here with: process.env.VITE_NAME
    // import.meta.env.VITE_PORT available here with: process.env.VITE_PORT
    return defineConfig({
               define: {
                     'process.env': process.env
              }
      })
}
```

**Comment by kshq1996** [comment]
建议官方还是改成 import.meta.env 更兼容一点

**Comment by lirongtong** [comment]
好的，谢谢，过些天时间比较充裕了我去看看，准备整合一些新功能上去。

发自我的iPhone

在 2021年4月23日，15:18，Mr.KeAng ***@***.***> 写道：

﻿

建议官方还是改成 import.meta.env 更兼容一点

**Comment by kshq1996** [comment]
能否单独出一个css文件 把 antdv 的默认样式 给全部覆盖掉？ 样式很好看 可惜我们已经开始用antdv开发了 不能替换组件 可以替换样式

**Comment by lirongtong** [comment]
哈，全部可能不会去单独覆盖，最近比较忙，不过用到的一些相关组件，基本上都已经测试覆盖到了
可以看看源码内的 style 文件夹，里面有个单独的 antd.less 就是针对 antd 组件库覆盖的

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: ***@***.***>
发送时间: 2021年4月26日 1:05
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [lirongtong/miitvip-vue-admin-manager] 直接引入使用默认的就会报错 是我哪里没写对吗？ (#4)


能否单独出一个css文件 把 antdv 的默认样式 给全部覆盖掉？ 样式很好看 可惜我们已经开始用antdv开发了 不能替换组件 可以替换样式

―
