### ISSUE TITLE
点击搜索，任意进入一个搜索项，页面空白，返回之后面包屑无法关闭

### ISSUE THREAD

**Issue by xxg233** [lirongtong/miitvip-vue-admin-manager#5]
![bug](https://user-images.githubusercontent.com/45847363/118905635-ab739b00-b94e-11eb-991c-05de90b62ba5.gif)

**Comment by lirongtong** [comment]
已经修正
路由改过几次，搜索内相呼应的路由忘记修正了，谢谢
