### ISSUE TITLE
代码demo预览

### ISSUE THREAD

**Issue by majinhui04** [lirongtong/miitvip-vue-admin-manager#6]
![](https://tva1.sinaimg.cn/large/008i3skNly1gsmaqvms4bj31iq0lsac9.jpg)
请问这个组件预览实现代码能开源吗

**Comment by lirongtong** [comment]
源码内都有的

> ![](https://camo.githubusercontent.com/45df5ce63f206964a98057af11f69c97e70b3e4bbb4096dd1e6615e72db4363a/68747470733a2f2f747661312e73696e61696d672e636e2f6c617267652f3030386933736b4e6c793167736d6171766d7334626a33316971306c736163392e6a7067)
> 请问这个组件预览实现代码能开源吗
